module.exports = {
  tailwindConfig: "./tailwind.config.js",
  arrowParens: "avoid",
  trailingComma: "none",
  tabWidth: 2,
  printWidth: 100,
  semi: false,
  singleQuote: true,
  plugins: [
    "@ianvs/prettier-plugin-sort-imports",
    "prettier-plugin-tailwindcss" // MUST come last
  ],
  pluginSearchDirs: false,
  importOrder: [
    "<TYPES>",
    "^@/types/(.*)$",
    "^@/assets/(.*)$",
    "^interfaces/(.*)$",
    "^next/(.*)$",
    "<THIRD_PARTY_MODULES>",
    "^@/api/(.*)$",
    "^@/store",
    "^@/redux/(.*)$",
    "^redux/(.*)$",
    "^utils/(.*)$",
    "^service/(.*)$",
    "^@/service/(.*)$",
    "^@/utils/(.*)$",
    "^helpers/(.*)$",
    "^@/helpers/(.*)$",
    "^proxy/(.*)$",
    "^hooks/(.*)$",
    "^@/hooks/(.*)$",
    "^meta/(.*)$",
    "^@/i18n/(.*)$",
    "^locale/(.*)$",
    "^const/(.*)$",
    "^@/features/(.*)$",
    "^features/(.*)$",
    "^@/pages/(.*)$",
    "^@/widgets/(.*)$",
    "^@/components/(.*)$",
    "app",
    "^components/(.*)$",
    "^(?!.*[.]scss$)[./].*$",
    "^theme/(.*)$",
    ".(s)css$"
  ],
  importOrderSeparation: false,
  importOrderSortSpecifiers: false
};
